# Generated by Django 4.2.11 on 2026-02-02 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_count', models.IntegerField(blank=True, null=True)),
                ('line_count', models.IntegerField(blank=True, null=True)),
                ('commit_count', models.IntegerField(blank=True, null=True)),
                ('top_languages', models.JSONField(blank=True, default=dict)),
                ('analysis_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='repositories.repository')),
            ],
            options={
                'db_table': 'analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='analyses_status_a2cfc9_idx'), models.Index(fields=['repository'], name='analyses_reposit_6a1e4d_idx')],
            },
        ),
    ]
