# Generated by Django 4.2.11 on 2026-02-02 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complexity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('creativity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('maintainability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('innovation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('organization_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True)),
                ('shape_type', models.CharField(choices=[('sphere', 'Sphere'), ('cube', 'Cube'), ('complex', 'Complex')], default='sphere', max_length=50)),
                ('complexity_level', models.IntegerField(default=5)),
                ('rotation_speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('particle_count', models.IntegerField(default=50)),
                ('personality_description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality', to='analyses.analysis')),
            ],
            options={
                'db_table': 'personalities',
            },
        ),
        migrations.CreateModel(
            name='CodeInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('patterns', 'Patterns'), ('issues', 'Issues'), ('strengths', 'Strengths')], max_length=100)),
                ('insight_text', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='info', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('line_numbers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='personalities.personality')),
            ],
            options={
                'db_table': 'code_insights',
                'ordering': ['category', 'severity'],
            },
        ),
        migrations.AddIndex(
            model_name='personality',
            index=models.Index(fields=['analysis'], name='personaliti_analysi_694112_idx'),
        ),
        migrations.AddIndex(
            model_name='personality',
            index=models.Index(fields=['complexity_score', 'creativity_score'], name='personaliti_complex_fadadb_idx'),
        ),
        migrations.AddIndex(
            model_name='codeinsight',
            index=models.Index(fields=['personality'], name='code_insigh_persona_37a02f_idx'),
        ),
        migrations.AddIndex(
            model_name='codeinsight',
            index=models.Index(fields=['category'], name='code_insigh_categor_77e552_idx'),
        ),
    ]
