# Generated by Django 4.2.11 on 2026-02-02 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], default='github', max_length=20)),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField(max_length=500, unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repositories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform'], name='repositorie_platfor_a7aad2_idx'), models.Index(fields=['owner'], name='repositorie_owner_9ddf69_idx'), models.Index(fields=['language'], name='repositorie_languag_9b73bf_idx')],
            },
        ),
    ]
